### PR TITLE
fixes parser

### PR DESCRIPTION
**Pull request by savar**
- there was an 'if' statement which was only true with some sort of naming
  schema but in the block it search for more than in the 'if' statement
  was allowed
- now it should only allow namings which are allowed (according to munin
  docs)

### CODE REVIEW

**Comment by sosedoff** [comment]
any idea how to reproduce the issue with munin node ?

**Comment by savar** [comment]
you have to find a munin plugin using a _ or number in it's attribute name.. df has normally _ in the names: 

```
require 'rubygems'
require 'munin-ruby'

node = Munin::Node.new
node.config 'df'

# old version
{"df"=>{"graph"=>{"args"=>{"parsed"=>{"l"=>"0", "upper-limit"=>"100"}, "raw"=>"--upper-limit 100 -l 0"}, "category"=>"disk", "scale"=>"no", "title"=>"Disk usage in percent", "vlabel"=>"%"}, "metrics"=>{}}}

# new version
=> {"df"=>{"graph"=>{"args"=>{"parsed"=>{"l"=>"0", "upper-limit"=>"100"}, "raw"=>"--upper-limit 100 -l 0"}, "category"=>"disk", "scale"=>"no", "title"=>"Disk usage in percent", "vlabel"=>"%"}, "metrics"=>{"_dev"=>{"critical"=>"98", "label"=>"/dev", "warning"=>"92"}, "_dev_shm"=>{"critical"=>"98", "label"=>"/dev/shm", "warning"=>"92"}, "_dev_cciss_c0d0p1"=>{"critical"=>"98", "label"=>"/boot", "warning"=>"92"}, "_lib_init_rw"=>{"critical"=>"98", "label"=>"/lib/init/rw", "warning"=>"92"}, "_dev_cciss_c0d0p3"=>{"critical"=>"98", "label"=>"/", "warning"=>"92"}}}}
```

**Comment by sosedoff** [comment]
Great, thanks!

**Comment by savar** [comment]
Thanks.. could you create a new version so that we're able to use 'gem install munin-ruby'?

**Comment by sosedoff** [comment]
Sure, will do.

**Comment by sosedoff** [comment]
released

**Comment by savar** [comment]
Thx!

**Pull request merged**
