### PR TITLE
Use Timeout or if available SystemTimer on connections.

### PR DESCRIPTION
**Pull request by barn**
Picked an arbitary number of seconds (ten) for how long to time out on network connections. Will use SystemTimer (http://ph7spot.com/musings/system-timer) if it's available, falls back to Timeout if not.

Currently running in my infrastructure (via munin2graphite), all day in fact, but it hasn't yet timed out typically.

### CODE REVIEW

**Comment by sosedoff** [comment]
Will merge, but needs some refactoring.

**Comment by barn** [comment]
Sweet. What's up with it? I like me blank lines, is that it?

**Comment by sosedoff** [comment]
Made some refactoring on master, can you test updates ?

**Comment by barn** [comment]
So at $WORK we ripped out our entire munin infrastructure and moved to collectd as it just wasn't working for us. So I'm afraid I can't test it any more. Sorry! ):

**Comment by sosedoff** [comment]
Any good reason to move to collectd ?

**Comment by barn** [comment]
we were using munin before and moved to graphite, so we were using the munin2graphite bridge. Which was just a band-aid on the situation. It kept breaking and it had to be monitored really heavily. Collected is designed to do this in a way munin+munin2graphite+work around it to make it work really wasn't.

**Pull request merged**
